config/routes.rb
Rails.application.routes.draw do
  
  resources :musician do
    resources :song
  end
  
  root 'musician#index'
end


#   Prefix Verb   URI Pattern                                      Controller#Action
#     musician_songs GET    /musicians/:musician_id/songs(.:format)          songs#index
#                    POST   /musicians/:musician_id/songs(.:format)          songs#create
#  new_musician_song GET    /musicians/:musician_id/songs/new(.:format)      songs#new
# edit_musician_song GET    /musicians/:musician_id/songs/:id/edit(.:format) songs#edit
#      musician_song GET    /musicians/:musician_id/songs/:id(.:format)      songs#show
#                    PATCH  /musicians/:musician_id/songs/:id(.:format)      songs#update
#                    PUT    /musicians/:musician_id/songs/:id(.:format)      songs#update
#                    DELETE /musicians/:musician_id/songs/:id(.:format)      songs#destroy
#          musicians GET    /musicians(.:format)                             musicians#index
#                    POST   /musicians(.:format)                             musicians#create
#       new_musician GET    /musicians/new(.:format)                         musicians#new
#      edit_musician GET    /musicians/:id/edit(.:format)                    musicians#edit
#           musician GET    /musicians/:id(.:format)                         musicians#show
#                    PATCH  /musicians/:id(.:format)                         musicians#update
#                    PUT    /musicians/:id(.:format)                         musicians#update
#                    DELETE /musicians/:id(.:format)                         musicians#destroy
#               root GET    /                                                musicians#index

app/models/musician.rb
class Musician < ActiveRecord::Base
end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/musician_controller.rb
class MusicianController < ApplicationController

  before_action :find_musician, only: [:edit, :show, :update, :destroy, :add_song, :remove_song]

  def index
    @musician = Musician.all
  end

  def new
    @musician = Musician.new
  end

  def show
  end

  def edit
  end

  def update
    @musician.update_attributes musician_params
    if @musician.save
      redirect_to "/musician/#{@musician.id}"
    else
      render :edit
    end
  end

  def destroy
    musician.destroy
    redirect_to '/musician'
  end

  def create
    @musician = Musician.new user_params
    if @musician.save
      redriect_to '/'
    else
      render :new
    end
  end

  def add_song
    song = Song.find(song_params[:id])
    unless @musician.include? song
      @musician.songs << song
    end
    redirect_to @musician
  end

  def remove_song
    @musician.songs.delete(song)
    redirect_to @musician
  end



  private
  def musician_params
    params.require(:musician).permit(:name)
  end

  def song_params
    params.require(:song).permit(:title)
  end

  def find_musician
    @musician = Musician.find(params[:id])
  end

end

app/controllers/song_controller.rb
class SongController < ApplicationController

  before_action :find_song, only: [:edit, :show, :update, :destroy]
  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
  end

  def show
  end

  def edit
  end

  def create
    Song.create song_params
    redirect_to songs_path
  end

  def update
    @song.update_attributes song_params
    redirect_to @song
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

  private
  def song_params
    params.require(:song).permit(:title)
  end

  def musician_params
    params.require(:musician).permit(:name)
  end

  def find_song
    @song = Song.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musician_helper.rb
module MusicianHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OtoMRailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/musician/edit.html.erb
<h1>Edit Musician</h1>

<%= form_for @musician do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/musician/index.html.erb
<h1>Musician</h1>


<ul>
  <% @musician.each do |musician| %>
  <li><%= link_to musician.name, actor_path(musician) %></li>
  <% end %>
</ul>

<%= link_to "Add new Musician", new_musician_path %>

app/views/musician/new.html.erb
<h1>Add a musician</h1>

<%= form_for @musician do |f| %>
  <%= f.text_field :name, :placeholder => "Name" %>
  <%= f.submit %>
<% end %>

app/views/musician/show.html.erb
<h1><%= @musician.name %></h1>

<div class="black-box">
  <h2>Songs</h2>
  <ul>
    <% @musician.songs.each do |song| %>
    <li>
      <%= link_to "#{song.title}", song_pat(song) %>
    </li>
    <% end %>
  </ul>

  <% unless @songs.empty? %>
    <%= form_tag add_song_path do |f| %>
      <%= collection_select :song, :id, @songs, :id, :title %>
      <%= submit_tag "Add" %>
    <% end %>
  <% end %>
</div>

app/views/song/edit.html.erb
<h1>Song#edit</h1>
<p>Find me in app/views/song/edit.html.erb</p>

app/views/song/index.html.erb
<h1>Song#index</h1>
<p>Find me in app/views/song/index.html.erb</p>

app/views/song/new.html.erb
<h1>Song#new</h1>
<p>Find me in app/views/song/new.html.erb</p>

app/views/song/show.html.erb
<h1>Song#show</h1>
<p>Find me in app/views/song/show.html.erb</p>